name: caramelo_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  google_fonts: ^8.0.1

  flutter_animate: ^4.5.2

  cached_network_image: ^3.4.1

  provider: ^6.1.5+1

  get_it: ^9.2.0

  shared_preferences: ^2.5.4

  go_router: ^17.1.0

  http: ^1.2.2

  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_native_splash: ^2.4.0

  flutter_launcher_icons: ^0.13.1


flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/png/

# dart run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/png/logo.png
  color: "#323232"
  color_dark: "#F8F8F8"
  android_12:
    image: assets/images/png/logo.png
    color: "#323232"
    color_dark: "#F8F8F8"

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/png/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#323232"
  adaptive_icon_foreground: "assets/images/png/logo.png"
  web:
    generate: true
    image_path: "assets/images/png/logo.png"
    background_color: "#hex_code"
    theme_color: "#hex_code"
  windows:
    generate: true
    image_path: "assets/images/png/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/png/logo.png"